version: '3'
services:
  sakila_db:
    build:
      context: docker
      dockerfile: Dockerfile.Sakila
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    command: ["-c", "shared_buffers=5GB", "-c","effective_cache_size=15GB","-c", "maintenance_work_mem=1280MB","-c", "checkpoint_completion_target=0.7", "-c","wal_buffers=16MB", "-c","default_statistics_target=100", "-c","random_page_cost=1.1", "-c","effective_io_concurrency=200","-c", "work_mem=26214kB","-c", "min_wal_size=1GB","-c", "max_wal_size=2GB" ,"-c", "max_worker_processes=4","-c", "max_parallel_workers_per_gather=2", "-c","max_parallel_workers=4"]
  eosm_db:
    build:
      context: docker
      dockerfile: Dockerfile.Eosm
    ports:
    - "5433:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    command: ["-c", "shared_buffers=5GB", "-c","effective_cache_size=15GB","-c", "maintenance_work_mem=1280MB","-c", "checkpoint_completion_target=0.7", "-c","wal_buffers=16MB", "-c","default_statistics_target=100", "-c","random_page_cost=1.1", "-c","effective_io_concurrency=200", "-c" ,"work_mem=26214kB","-c", "min_wal_size=1GB", "-c","max_wal_size=2GB" ,"-c", "max_worker_processes=4","-c", "max_parallel_workers_per_gather=2", "-c","max_parallel_workers=4"]
  postgraphile_sakila:
    build:
      context: docker
      dockerfile: Dockerfile.Postgraphile
    ports:
    - "5001:5001"
    entrypoint: dockerize -wait tcp://sakila_db:5432 -timeout 30s
    command: postgraphile --connection postgres://postgres:mysecretpassword@sakila_db:5432/sakila --host 0.0.0.0 --port 5001 --schema public --watch --enhance-graphiql --append-plugins postgraphile-plugin-connection-filter @graphile/postgis @graphile-contrib/pg-order-by-related
  postgraphile_eosm:
    build:
      context: docker
      dockerfile: Dockerfile.Postgraphile
    ports:
    - "5002:5002"
    entrypoint: dockerize -wait tcp://eosm_db:5432 -timeout 30s
    command: postgraphile --connection postgres://postgres:mysecretpassword@eosm_db:5432/eosm_ch --host 0.0.0.0 --port 5002 --schema public --watch --enhance-graphiql --append-plugins postgraphile-plugin-connection-filter @graphile/postgis @graphile-contrib/pg-order-by-related
  postgrest_sakila:
    image: "postgrest/postgrest"
    ports:
    - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:mysecretpassword@sakila_db:5432/sakila
      PGRST_DB_ANON_ROLE: postgres
      PGRST_DB_SCHEMA: public
    depends_on:
      - sakila_db
  swagger_sakila:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
    depends_on:
      - postgrest_sakila
  postgrest_eosm:
    image: "postgrest/postgrest"
    ports:
    - "3001:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:mysecretpassword@eosm_db:5432/eosm_ch
      PGRST_DB_ANON_ROLE: postgres
      PGRST_DB_SCHEMA: public
    depends_on:
      - sakila_db
  swagger_eosm:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    expose:
      - "8081"
    environment:
      API_URL: http://localhost:3001/
    depends_on:
      - postgrest_sakila