FROM mdillon/postgis:11

ADD data/sakila.sql /
ADD data/sakila_views.sql /
ADD data/sakila_prewarm.sql /
ADD data/sakila_init.sh /docker-entrypoint-initdb.d/


RUN chmod +x /docker-entrypoint-initdb.d/sakila_init.sh
