FROM mdillon/postgis:11

ADD data/eosm_ch.sql /
ADD data/eosm_ch_fix.sql /
ADD data/eosm_views.sql /
ADD data/eosm_prewarm.sql /
ADD data/eosm_init.sh /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/eosm_init.sh
RUN chmod +x /eosm_ch_fix.sql